// -----------------------------------------------------------
//                      INITIALISATION
// -----------------------------------------------------------
// tableau 
let words=["ABALONE","ABALONES","ABDUCTION","ABDUCTIONS","ABERRANT","ABERRANTS","ABRACADABRA","ABRACADABRAS","ABRAXAS","ACROBATES","ACROSTICHE","ACROSTICHES","ACTIONNAIRE","ACTIONNAIRES","ADDICT","ADDICTS","ADJUGE","ADJUGES","AFICIONADO","AFICIONADOS","AGENT","AGENTS","AGGRAVATION","AGGRAVATIONS","AGORA","AGORAS","AIDEAU","AIDEAUX","ALARME","ALARMES","ALBEDO","ALBEDOS","ALCAZAR","ALCAZARS","ALEA","ALEAS","ALIAS","ALIBI","ALIBIS","ALIENS","ALLIANCE","ALLIANCES","ALPAGES","ALUETTE","ALUETTES","AMAZONE","AMAZONES","AMBIGU","AMBIGUS","AMBITION","AMBITIONS","AMBRE","AMBRES","AMERICAIN","AMERICAINS","AMIRAUTE","AMIRAUTES","ANACROISES","ANAGRAMME","ANAGRAMMES","ANCIENNE","ANCIENNES","ANE","ANES","ANGUILLE","ANGUILLES","ANIMA","ANIMAS","ANNEAU","ANNEAUX","ANNEE","ANNEES","ANNEXION","ANNEXIONS","ANTIQUE","ANTIQUES","APACHE","APACHES","APOCALYPSE","APOCALYPSES","AQUARIUM","AQUARIUMS","ARA","ARAIGNEE","ARAIGNEES","ARAS","ARBALETE","ARBALETES","ARBORA","ARBORAS","ARCHIPEL","ARCHIPELS","ARENA","ARENAS","ARENE","ARENES","ARISTO","ARISTOS","ARLEQUIN","ARLEQUINS","ARMADA","ARMADAS","ASCENSEUR","ASCENSEURS","ASCENSION","ASCENSIONS","ASSASSIN","ASSASSINS","ASSAUT","ASSAUTS","ASSIETTE","ASSIETTES","ATRIUM","ATRIUMS","ATTAQUE","ATTAQUES","ATTRACTION","ATTRACTIONS","ATTRAPE","ATTRAPES","ATTRIBUT","ATTRIBUTS","AUTOROUTE","AUTOROUTES","AUTOSTOP","AUTOSTOPS","AVALANCHE","AVALANCHES","AVENTURIERS","AWALE","AWALES","AWELE","AWELES","BACCALAUREAT","BACCALAUREATS","BACCARA","BACCARAS","BACCHANALES","BACKGAMMON","BACKGAMMONS","BADABOUM","BAGATELLE","BAGATELLES","BAGOU","BAGOUS","BAGUENAUDIER","BAGUENAUDIERS","BAGUES","BALAI","BALAIS","BALAN","BALANCE","BALANCES","BALLAST","BALLASTS","BALLE","BALLES","BALLON","BALLONS","BALTHAZAR","BALTHAZARS","BAMBOUS","BANCO","BANCOS","BANDA","BANDAS","BANQUISE","BANQUISES","BANTU","BANTUS","BANZAI","BAQUET","BAQUETS","BARAQUE","BARAQUES","BARATIN","BARATINS","BARBOTTE","BARBOTTES","BARBU","BARBUS","BARON","BARONS","BARRACUDA","BARRACUDAS","BARRES","BARRICADE","BARRICADES","BASCULE","BASCULES","BASIC","BASICS","BASKET","BASKETS","BASSETTE","BASSETTES","BASTIDE","BASTIDES","BASTON","BASTONS","BATACLAN","BATACLANS","BATAILLE","BATAILLES","BATAVIA","BATAVIAS","BATIK","BATIKS","BATONNETS","BELLIGERANTS","BELOTE","BELOTES","BENGALI","BENGALIS","BERET","BERETS","BERGER","BERGERS","BESIGUE","BESIGUES","BETE","BETES","BETISIER","BETISIERS","BIDET","BIDETS","BILBOQUET","BILBOQUETS","BILLARD","BILLARDS","BILLE","BILLES","BILLON","BILLONS","BINGO","BINGOS","BINOCLE","BINOCLES","BIRIBI","BIRIBIS","BISON","BISONS","BITUME","BITUMES","BLUFF","BLUFFER","BLUFFS","BOG","BOGS","BOLIDES","BOMBE","BOMBES","BONGO","BONGOS","BONNETEAU","BONNETEAUX","BOOMERANG","BOOMERANGS","BOSSE","BOSSES","BOSTON","BOSTONS","BOUC","BOUCLES","BOUCS","BOUILLOTTE","BOUILLOTTES","BOULE","BOULES","BOULIER","BOULIERS","BOUM","BOUMS","BOURRE","BOURRES","BOURRICOT","BOURRICOTS","BOURRU","BOURRUS","BOURSE","BOURSES","BOUTEILLE","BOUTEILLES","BRELAN","BRELANS","BRIDGE","BRIDGES","BRILLANCE","BRILLANCES","BRISQUE","BRISQUES","BROCANTE","BROCANTES","BROUHAHA","BROUHAHAS","BUCHER","BUCHERS","BUNKER","BUNKERS","BURGER","BURGERS","BUSHIDO","BUSHIDOS","BUSINESS","BUT","BUTEUR","BUTEURS","BUTS","BUTTE","BUTTES","CABALE","CABALES","CABRIOLET","CABRIOLETS","CACHETTE","CACHETTES","CAILLOU","CAILLOUX","CALCULA","CALCULAS","CALYPSO","CALYPSOS","CAMELEON","CAMELEONS","CAMELOT","CAMELOTS","CAMOUFLAGE","CAMOUFLAGES","CAMPAGNOL","CAMPAGNOLS","CAMPANILE","CAMPANILES","CAMPUS","CANASTA","CANASTAS","CANCRES","CANISSE","CANISSES","CANNES","CANONNIERS","CANYON","CANYONS","CAPHARNAUM","CAPHARNAUMS","CAPRICE","CAPRICES","CAPTURES","CARABISTOUILLE","CARABISTOUILLES","CARACOLE","CARACOLES","CARACTERE","CARACTERES","CARAIBES","CARAMBA","CARAMBOUILLE","CARAMBOUILLES","CARAVANE","CARAVANES","CARGO","CARGOS","CARIOCA","CARIOCAS","CARRE","CARRES","CARRIER","CARRIERES","CARRIERS","CARROM","CARROMS","CARROUSEL","CARROUSELS","CARTES","CASAQUE","CASAQUES","CASBAH","CASBAHS","CASH","CASHS","CASINO","CASINOS","CASQUETTE","CASQUETTES","CASTEL","CASTELS","CATAPULTE","CATAPULTES","CATHEDRAL","CELLULES","CENDRES","CERCEAU","CERCEAUX","CHALLENGE","CHALLENGES","CHAMPIONS","CHANDELIER","CHANDELIERS","CHANDELLE","CHANDELLES","CHANTIER","CHANTIERS","CHAPEAU","CHAPEAUX","CHARADE","CHARADES","CHARIOT","CHARIOTS","CHARRET","CHARRETS","CHAT","CHATEAU","CHATEAUX","CHATS","CHENILLE","CHENILLES","CHEPTEL","CHEPTELS","CHEVRE","CHEVRES","CHIBRE","CHIBRES","CHICOREE","CHICOREES","CHIEN","CHIENS","CHIMERES","CHINA","CHINAS","CHIQUE","CHIQUES","CHOUINE","CHOUINES","CIBLE","CIBLES","CINEMA","CINEMAS","CIRCUIT","CIRCUITS","CITADELLE","CITADELLES","CITE","CITES","CITOYENNETE","CITOYENNETES","CIVILISATION","CIVILISATIONS","CLAIM","CLAIMS","CLANS","CLE","CLES","CLIPPERS","CLOU","CLOUS","CLOWN","CLOWNS","COCHONNET","COCHONNETS","COCHONS","COCORICO","COCORICOS","CODE","CODES","COINCHE","COINCHES","COMBINARD","COMBINARDS","COMBO","COMBOS","COMMERE","COMMERES","CON","CONCORDANCES","CONDOTTIERE","CONDOTTIERES","CONFERENCE","CONFERENCES","CONFRONTATION","CONFRONTATIONS","CONFUSION","CONFUSIONS","CONNEXION","CONNEXIONS","CONQUETE","CONQUETES","CONQUISTADOR","CONQUISTADORS","CONS","CONSPIRATEURS","CONSPIRATIONS","CONSTELLATION","CONSTELLATIONS","CONTACT","CONTACTS","CONTINUO","CONTINUOS","CONTRA","CONTRARIO","CONTRAS","CONTREE","CONTREES","CONTROVERSE","CONTROVERSES","COPS","COQUELICOT","COQUELICOTS","CORBEILLE","CORBEILLES","CORDA","CORDAS","CORDE","CORDES","CORNER","CORNERS","CORPORATION","CORPORATIONS","CORRIDA","CORRIDAS","CORRUPTION","CORRUPTIONS","CORSAIRE","CORSAIRES","COSMOS","COUCOU","COUCOUS","COUILLON","COUILLONS","COUP","COUPEZ","COUPLES","COUPS","COURATE","COURATES","COURONNE","COURONNES","COURTISANS","COUYON","COUYONS","COYOTE","COYOTES","CRACK","CRACKS","CRAPAUD","CRAPAUDS","CRAPETTE","CRAPETTES","CRAPS","CREDO","CREDOS","CRESCENDO","CRESCENDOS","CRESUS","CRIB","CRIBS","CRICKET","CRICKETS","CRIMES","CRIQUET","CRIQUETS","CROISADES","CROIX","CROQUET","CROQUETS","CROSS","CROSSE","CROSSES","CRYPTOGAME","CRYPTOGAMES","CUBA","CUBAS","CUBE","CUBES","DADA","DADAS","DAIMYO","DAIMYOS","DALLES","DAMES","DANGER","DANGERS","DAO","DAOS","DARJEELING","DARJEELINGS","DE","DECOUVREUR","DECOUVREURS","DEDALES","DEFI","DEFIS","DEGOMME","DEGOMMES","DELTA","DELTAS","DERBY","DERBYS","DERIVE","DERIVES","DES","DESTINS","DEVINETTE","DEVINETTES","DIABOLO","DIABOLOS","DIADOQUES","DIAM","DIAMANT","DIAMANTS","DIAMS","DICO","DICOS","DICTIONNAIRE","DICTIONNAIRES","DIGIT","DIGITS","DINETTE","DINETTES","DINGBATS","DINGO","DINGOS","DIPLOMATIE","DIPLOMATIES","DISPOSITION","DISPOSITIONS","DISPUTE","DISPUTES","DIVERTIMENTO","DIVERTIMENTOS","DIXIT","DOCKERS","DOGE","DOGES","DOMINO","DOMINOS","DON","DONS","DOTS","DOUBLE","DOUBLES","DOUBLETTE","DOUBLETTES","DRAGON","DRAGONS","DRAGSTER","DRAGSTERS","DRAKKAR","DRAKKARS","DRAPEAU","DRAPEAUX","DROGUE","DROGUES","DRUMLIN","DRUMLINS","DUEL","DUELS","DUNE","DUNES","DUO","DUOS","DYADE","DYADES","EAU","EAUX","ECARTE","ECARTES","ECHANGE","ECHANGES","ECHAPPEE","ECHAPPEES","ECHASSES","ECHECS","ECHELLE","ECHELLES","ECOLOGIE","ECOLOGIES","ECONOMIE","ECONOMIES","ECU","ECUS","ECUSSON","ECUSSONS","EDEN","EDENS","EGALITE","EGALITES","EGO","EGYPTIEN","EGYPTIENS","EJECTION","EJECTIONS","ELASTIQUE","ELASTIQUES","ELECTRO","ELECTROS","ELEMENTS","ELITES","ELIXIR","ELIXIRS","EMBUSCADES","EMIGRETTE","EMIGRETTES","EMPIRE","EMPIRES","ENCANTEUR","ENCANTEURS","ENCLOS","ENERGIE","ENERGIES","ENFLE","ENFLES","ENGRENAGE","ENGRENAGES","ENIGME","ENIGMES","ENTRAVE","ENTRAVES","EPERVIER","EPERVIERS","EQUILIBRE","EQUILIBRES","EQUIPE","EQUIPES","ERREURS","ESCALIER","ESCALIERS","ESPERANCE","ESPERANCES","ESPIONNAGE","ESPIONNAGES","ETOILE","ETOILES","EUREKA","EXCELLENCE","EXCELLENCES","EXIT","EXPEDITION","EXPEDITIONS","EXPERTS","EXPORTATION","EXPORTATIONS","EXPOS","EXPRES","EXPRESS","EXPRESSION","EXPRESSIONS","EXPRESSO","EXPRESSOS","FACTEUR","FACTEURS","FAKIR","FAKIRS","FANTOMES","FARANDOLE","FARANDOLES","FARO","FAROS","FASCINATION","FASCINATIONS","FEERIE","FEERIES","FEODALITE","FEODALITES","FER","FERME","FERMES","FERS","FESTIVAL","FESTIVALS","FICELLE","FICELLES","FIEF","FIEFS","FIGARO","FIGAROS","FILOU","FILOUS","FINALE","FINALES","FINANCE","FINANCES","FINESSE","FINESSES","FINISH","FINISHS","FITS","FLAMBEUR","FLAMBEURS","FLASH","FLASHS","FLECHETTES","FLIBUSTIERS","FLIP","FLIPPER","FLIPPERS","FLIPS","FLORENTIN","FLORENTINS","FLUX","FOCAL","FOCUS","FONCTIONNAIRE","FONCTIONNAIRES","FOOT","FOOTS","FORCE","FORCES","FORESTIERE","FORESTIERES","FORMA","FORMAS","FORMICA","FORMICAS","FORTERESSE","FORTERESSES","FORTISSIMO","FRAGILE","FRAGILES","FRAGRANCES","FRANCAISE","FRANCAISES","FRANCOPHILE","FRANCOPHILES","FRISBEE","FRISBEES","FRONTIERES","FRUITS","FUDGE","FUDGES","FUGITIFS","FURET","FURETS","GALETS","GALOCHE","GALOCHES","GAMATE","GAMATES","GAMELLE","GAMELLES","GANGSTER","GANGSTERS","GARCON","GARCONS","GAUDI","GAUDIS","GENIAL","GEO","GEOS","GERBE","GERBES","GIN","GINS","GLISSADE","GLISSADES","GO","GONDOLIER","GONDOLIERS","GORE","GORES","GOS","GOSSE","GOSSES","GOUREN","GOURENS","GOUTER","GOUTERS","GRAAL","GRAALS","GRACES","GRACIAS","GRANITO","GRANITOS","GRENOUILLE","GRENOUILLES","GREYHOUNDS","GRIMACES","GUILDES","GUILLOTINE","GUILLOTINES","GUIMBARDE","GUIMBARDES","GUISE","GYMKHANA","GYMKHANAS","HABILLAGE","HABILLAGES","HALLOWEEN","HALLOWEENS","HAMBURGER","HAMBURGERS","HAMSTERS","HANDICAP","HANDICAPS","HANTISE","HANTISES","HASARD","HASARDS","HELICE","HELICES","HERE","HERES","HERISSONS","HERMINE","HERMINES","HEXAGONE","HEXAGONES","HIGHLANDERS","HOCA","HOCAS","HOLDING","HOLDINGS","HOMBRE","HOMBRES","HONCHETS","HONGROIS","HOROSCOPE","HOROSCOPES","HOTEL","HOTELS","HUIT","HURLEMENTS","HUSSARDS","HYENE","HYENES","ICEBERG","ICEBERGS","ILES","IMAGES","IMAGINE","IMAGINES","IMMOBILIER","IMMOBILIERS","IMMORTEL","IMMORTELS","IMPERIAL","IMPERIALE","IMPERIALES","IMPERIUM","IMPERIUMS","IMPRESARIO","IMPRESARIOS","INAVOUABLE","INAVOUABLES","INCOGNITO","INCOGNITOS","INCOLLABLES","INCROYABLE","INCROYABLES","INDUS","INFLUENCES","INITIALES","INPUT","INPUTS","INSTINCT","INSTINCTS","INTEMPERIES","INTERACTION","INTERACTIONS","INTRIGUE","INTRIGUES","INTRUS","INTUITION","INTUITIONS","INVASION","INVASIONS","ISOLA","ISOLAS","IVE","IVES","JACQUET","JACQUETS","JARDINAGE","JARDINAGES","JASS","JAVA","JAVAS","JAVELOT","JAVELOTS","JEU","JEUX","JOCKEY","JOCKEYS","JOKARI","JOKARIS","JONCHETS","JONGLAGE","JONGLAGES","JUMEAUX","JUMP","JUMPS","JUNGLE","JUNGLES","KAISER","KAISERS","KALEIDOSCOPE","KALEIDOSCOPES","KAMI","KAMIS","KANGOUROU","KANGOUROUS","KENDO","KENDOS","KREMLIN","KREMLINS","KRIEGSPIEL","KRIEGSPIELS","LABYRINTHE","LABYRINTHES","LANSQUENET","LANSQUENETS","LANTURLU","LANTURLUS","LAPINS","LAUREAT","LAUREATS","LEGO","LEGOS","LIBERTE","LIBERTES","LICES","LIEGE","LIEGES","LINDOR","LINDORS","LINOTTE","LINOTTES","LIVREURS","LOBA","LOBAS","LOCO","LOCOS","LOGIGRILLE","LOGIGRILLES","LOOPING","LOOPINGS","LOTERIE","LOTERIES","LOTO","LOTOS","LOTUS","LOUP","LOUPS","LOUTRE","LOUTRES","LUETTE","LUETTES","LUTINERIE","LUTINERIES","LYNX","MABOULS","MACADAM","MACADAMS","MACHER","MAELSTROM","MAELSTROMS","MAESTRO","MAESTROS","MAFIA","MAFIAS","MAGIE","MAGIES","MAGISTRAL","MAGNA","MAGNAS","MAGOT","MAGOTS","MAHARADJAH","MAHARADJAHS","MAHARAJA","MAHARAJAS","MAIL","MAILLETS","MAILS","MALABARS","MALEFICES","MAMBA","MAMBAS","MAMMA","MAMMAS","MANA","MANAGER","MANAGERS","MANAS","MANDARIN","MANDARINS","MANEGE","MANEGES","MANILLA","MANILLAS","MANILLE","MANILLES","MANIPULATEUR","MANIPULATEURS","MANITOU","MANITOUS","MANNEQUINS","MANOEUVRE","MANOEUVRES","MAO","MAOS","MARABOUT","MARABOUTS","MARELLE","MARELLES","MARIAGE","MARIAGES","MARIEE","MARIEES","MARK","MARKETING","MARKETINGS","MARKS","MARQUIS","MARTEAU","MARTEAUX","MASCARADE","MASCARADES","MASSACRE","MASSACRES","MASSAI","MASSAIS","MATADOR","MATADORS","MAYA","MAYAS","MECCANO","MECCANOS","MEDIEVAL","MEDINA","MEDINAS","MEDITERRANEE","MEDITERRANEES","MEDIUM","MEDIUMS","MEGA","MEGALO","MEGALOS","MEGAS","MEMOIRE","MEMOIRES","MENHIR","MENHIRS","MENTEUR","MENTEURS","MERCI","MERCIS","MERLIN","MERLINS","MESOPOTAMIEN","MESOPOTAMIENS","METAGRAMME","METAGRAMMES","METALLURGIE","METALLURGIES","METAMORPHOSE","METAMORPHOSES","METRO","METROS","MEUH","MEULE","MEULES","MIAM","MIKADO","MIKADOS","MILLIONNAIRE","MILLIONNAIRES","MIME","MIMES","MINESTRONE","MINESTRONES","MIROIR","MIROIRS","MISE","MISES","MISTIGRI","MISTIGRIS","MOAI","MOAIS","MOLLE","MOLLES","MONEGASQUE","MONEGASQUES","MONOPOLY","MONOPOLYS","MONTGOLFIERE","MONTGOLFIERES","MONTJOIE","MONTJOIES","MORFALS","MORPION","MORPIONS","MOT","MOTS","MOTUS","MOUCHE","MOUCHES","MOUCHOIR","MOUCHOIRS","MOULIN","MOULINS","MOURRE","MOURRES","MUS","MUSTANGS","MUTANTS","MYTHOS","NAINS","NAPOLEON","NAPOLEONS","NAPOLITAINE","NAPOLITAINES","NAUFRAGES","NEGOCES","NEUF","NEUFS","NEURONES","NEUTRON","NEUTRONS","NIGAUD","NIGAUDS","NINJA","NINJAS","NUGGETS","OASIS","OBSERVATEUR","OBSERVATEURS","OCEAN","OCEANS","OCTOGONE","OCTOGONES","ODYSSEE","ODYSSEES","OHE","OIE","OLE","OLYMPIQUES","OMEGA","ONYX","ONZE","OPTION","OPTIONS","ORDO","ORIENTE","ORIENTES","ORIGAMI","ORIGAMIS","OSSELETS","OTHELLO","OTHELLOS","OURSON","OURSONS","OUT","OVNI","OVNIS","OXO","PACHINKO","PACHINKOS","PAF","PAFS","PAGODE","PAGODES","PAIRES","PALA","PALABRES","PALADIN","PALADINS","PALANQUEE","PALANQUEES","PALAS","PALET","PALETA","PALETAS","PALETS","PANDEMONIUM","PANDEMONIUMS","PANIER","PANIERS","PAPARAZZI","PAPARAZZIS","PAPILLON","PAPILLONS","PARADIS","PARANOIA","PARANOIAS","PARCOURS","PARESSEUX","PARI","PARIS","PARRAIN","PARRAINS","PASSERELLES","PATATRAS","PATIENCE","PATIENCES","PATIO","PATIOS","PAUME","PAUMES","PECHEUR","PECHEURS","PEDALO","PEDALOS","PELOTON","PELOTONS","PENDU","PENDUS","PENNY","PENNYS","PENTE","PENTES","PERIPETIES","PERLES","PHARAON","PHARAONS","PHILIPPINE","PHILIPPINES","PHOENIX","PIANO","PIANOS","PICKPOCKET","PICKPOCKETS","PIEGES","PILOU","PILOUS","PIN","PINACLE","PINACLES","PINCETTE","PINCETTES","PINGOUIN","PINGOUINS","PINS","PIPELINE","PIPELINES","PIQUET","PIQUETS","PIRANHA","PIRANHAS","PIRATES","PISTE","PISTES","PITCH","PITCHS","PIVOT","PIVOTS","PLANETAIRE","PLANETAIRES","PLATEAU","PLATEAUX","PLEIADES","PLIAGE","PLIAGES","PLOMBIER","PLOMBIERS","POGO","POGOS","POINT","POINTS","POIRIER","POIRIERS","POISON","POISONS","POKER","POKERS","POLYGONE","POLYGONES","POMME","POMMES","POMMIER","POMMIERS","PONEYS","PONT","PONTS","POPOTAMO","POQUE","POQUES","PORTRAIT","PORTRAITS","POT","POTERIE","POTERIES","POTS","POUILLEUX","POULPE","POULPES","POUSSETTE","POUSSETTES","POUTRE","POUTRES","POUX","PRAIRIE","PRAIRIES","PREDATEURS","PREFERENCE","PREFERENCES","PRESIDENT","PRESIDENTS","PRIME","PRIMES","PRISES","PROBE","PROBES","PROVOCATION","PROVOCATIONS","PUANT","PUANTS","PUCE","PUCES","PUCIER","PUCIERS","PUEBLO","PUEBLOS","PUZZLE","PUZZLES","PYRAMIDE","PYRAMIDES","QIN","QINS","QUADRILATERE","QUADRILATERES","QUADRILLE","QUADRILLES","QUADS","QUANTUM","QUANTUMS","QUARTE","QUARTES","QUARTO","QUICK","QUICKS","QUID","QUILLE","QUILLES","QUINE","QUINES","QUINTE","QUINTES","QUINTO","QUINZE","QUIZ","RA","RAFLE","RAFLES","RAGE","RAGES","RAIL","RAILS","RAJA","RAJAS","RALLYE","RALLYES","RAMI","RAMIS","RAMPEAU","RAMPEAUX","RANCH","RANCHS","RANDONNEE","RANDONNEES","RAPIDO","RAPIDOS","RAPPEL","RAPPELS","RAS","RASANT","RASANTS","RAZZIA","RAZZIAS","REACTION","REACTIONS","REBOT","REBOTS","REBUS","REFLEXION","REFLEXIONS","REGATES","REGENCE","REGENCES","RENAISSANCE","RENAISSANCES","RENARD","RENARDS","REPORTAGES","REQUIN","REQUINS","RESTAURANT","RESTAURANTS","REUSSITE","REUSSITES","REVELATIONS","REVERSI","REVERSIS","REVOLUTION","REVOLUTIONS","RIBAUDS","RICHELIEU","RICHELIEUS","RICHELIEUX","RIFLE","RIFLES","RIFTS","RIKIKI","RIKIKIS","RIME","RIMES","RIO","RIOS","RIPOUX","RISQUE","RISQUES","ROBERT","ROBERTS","RODEO","RODEOS","ROI","ROIS","ROLE","ROLES","RONDE","RONDES","RONDO","RONDOS","RONFLE","RONFLES","ROUE","ROUES","ROULETTE","ROULETTES","ROUTARD","ROUTARDS","RUCHE","RUCHES","RUGBY","RUGBYS","RUNE","RUNES","SABOT","SABOTAGE","SABOTAGES","SABOTEUR","SABOTEURS","SABOTS","SAFARI","SAFARIS","SAGA","SAGAS","SAGESSE","SAGESSES","SALAMI","SALAMIS","SALIERE","SALIERES","SALVE","SALVES","SAMOURAI","SAMOURAIS","SAMURAI","SAMURAIS","SARDINES","SAUTERELLE","SAUTERELLES","SAVATE","SAVATES","SCARABEE","SCARABEES","SCENARIO","SCENARIOS","SCOOP","SCOOPS","SCOPA","SCOPAS","SCORE","SCORES","SCORPION","SCORPIONS","SCOUT","SCOUTS","SCRABBLE","SCRABBLES","SENAT","SENATS","SEPT","SEQUENCE","SEQUENCES","SERPENT","SERPENTS","SESAME","SESAMES","SET","SETS","SHAMAN","SHAMANS","SHIT","SHITS","SHOGI","SHOGIS","SHOGUN","SHOGUNS","SHOOT","SHOOTS","SIDERAL","SIEGE","SIEGES","SIESTA","SIESTAS","SIFFLET","SIFFLETS","SIGNAL","SILLAGE","SILLAGES","SIMULACRES","SINGE","SINGES","SIOUX","SIROCCO","SIROCCOS","SIX","SIXTE","SIXTES","SKAT","SKATS","SNOOKER","SNOOKERS","SNOWBOARD","SNOWBOARDS","SOCIETE","SOCIETES","SOLEIL","SOLEILS","SOLITAIRE","SOLITAIRES","SOLO","SOLOS","SONATE","SONATES","SORCELLERIE","SORCELLERIES","SORCIER","SORCIERE","SORCIERES","SORCIERS","SORTIE","SORTIES","SORTS","SOSIES","SOULE","SOULES","SPEED","SPEEDS","SPHINX","SPIDER","SPIDERS","SPONSOR","SPONSORS","SPRINTER","SPRINTERS","STATUES","STOP","STOPS","STRATEGES","STUD","STUDS","SUBITO","SUCCES","SUDOKU","SUDOKUS","SULTAN","SULTANS","SUMO","SUMOS","SUPPORTERS","SUPREMATIE","SUPREMATIES","SURVIVANT","SURVIVANTS","SUSPENS","SUSPENSE","SUSPENSES","SUZERAIN","SUZERAINS","SWITCH","SWITCHES","SWITCHS","SYLLABUS","SYMPATHIE","SYMPATHIES","TABERNACLE","TABERNACLES","TABOU","TABOUS","TAC","TACS","TALISMAN","TALISMANS","TANAGRA","TANAGRAS","TANDEM","TANDEMS","TANGAGE","TANGAGES","TANGO","TANGOS","TANGRAM","TANGRAMS","TAPE","TAPES","TAPETTE","TAPETTES","TAQUETS","TAQUIN","TAQUINS","TARA","TARAS","TARATATA","TARGUI","TARGUIS","TARIN","TARINS","TAROT","TAROTS","TAS","TAUREAU","TAUREAUX","TAUROMACHIE","TAUROMACHIES","TEMPLES","TENNIS","TERRA","TERRAS","THEQUE","THEQUES","TIERCE","TIERCES","TILT","TILTS","TIPI","TIPIS","TITAN","TITANS","TITUS","TOC","TOCS","TOMAHAWK","TOMAHAWKS","TOMATE","TOMATES","TOMBEURS","TOMBOLA","TOMBOLAS","TONNEAU","TONNEAUX","TONNELET","TONNELETS","TONTINE","TONTINES","TOPS","TOQUE","TOQUES","TORDU","TORDUS","TOTEM","TOTEMS","TOTON","TOTONS","TOUCHE","TOUCHES","TOUPIE","TOUPIES","TOUR","TOURS","TRAC","TRACS","TRAFIC","TRAFICS","TRAJECTOIRES","TRAME","TRAMES","TRANSAT","TRANSATS","TRANSFUGE","TRANSFUGES","TRAQUEUR","TRAQUEURS","TRAUMA","TRAUMAS","TRAVELLER","TRAVELLERS","TRAX","TREIZE","TRESOR","TRESORS","TRIAGE","TRIAGES","TRIANGLES","TRIAS","TRIBUN","TRIBUNS","TRIBUS","TRICTRAC","TRICTRACS","TRINOME","TRINOMES","TRIO","TRIOLET","TRIOLETS","TRIOMPHE","TRIOMPHES","TRIOS","TRIPLEX","TRIREME","TRIREMES","TROIKA","TROIKAS","TROT","TROTS","TRUIE","TRUIES","TRUST","TRUSTS","TUNE","TUNES","TURBO","TURBOS","TURFISTE","TURFISTES","TURQUOISE","TURQUOISES","TWISTER","TYPO","TYPOS","ULTIMO","URGENCE","URGENCES","VACHE","VACHES","VACHETTE","VACHETTES","VALETS","VAMPIRE","VAMPIRES","VEDETTES","VENDETTA","VENDETTAS","VERDICT","VERDICTS","VERGER","VERGERS","VERITE","VERITES","VERMINE","VERMINES","VERNISSAGE","VERNISSAGES","VERRAT","VERRATS","VERSANT","VERSANTS","VERSO","VERSOS","VERTIGES","VERTIGO","VERTIGOS","VESSIE","VESSIES","VETILLE","VETILLES","VIADUC","VIADUCS","VICAIRE","VICAIRES","VIGIES","VIKINGS","VILLAGES","VIRUS","VISITEURS","VITRAIL","VOCAL","VOGELPIK","VOGELPIKS","VOILE","VOILES","VOLANT","VOLANTS","VOLAPUK","VOLAPUKS","VOLCANS","VOLEUR","VOLEURS","VOLTAIRE","VOLTAIRES","VROOM","WALE","WALES","WALI","WALIS","WARGAME","WARGAMES","WASABI","WASABIS","WHIST","WHISTS","WIGWAM","WIGWAMS","YAM","YAMS","YASS","YASSE","YASSES","ZANZI","ZANZIBAR","ZANZIBARS","ZANZIS","ZERO","ZEROS","ZOMBIES","ZONE","ZONES","ZOO","ZOOS"];
let alphabet = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
let imageTab = ['./assets/image0.jpg', './assets/image1.jpg', './assets/image2.jpg', './assets/image3.jpg', './assets/image4.jpg', './assets/image5.jpg', './assets/image6.jpg', './assets/image7.jpg', './assets/image8.jpg']
//let leagueOfLegends = ["Morgana","Taliyah","Katarina","Malzahar","Zed","Fizz","Vladimir","VelKoz","Lux","Karthus","Nocturne","Annie","Anivia","Yasuo","Veigar","Ziggs","TwistedFate","Ekko","Zilean","Jayce","Aatrox","Leblanc","JarvanIV","Hecarim","Vi","Karthus","Rammus","Graves","Evelynn","Kha'Zix","Jax","XinZhao","Elise","Shaco","Kindred","Kayn","Amumu","Ivern","Udyr","Warwick","Pantheon","Volibear","Nidalee","Shyvana","MasterYi","Zac","Rengar","Kled","Darius","Jayce","Vladimir","Urgot","Sion","Pantheon","Kayle","Malphite","Yasuo","Camille","Aatrox","Hecarim","Illaoi","Karma","Rumble","Olaf","Irelia","Quinn","Vayne","Lissandra","Wukong","Singed","Volibear","Poppy","Fiora","Cassiopeia","Viktor","Draven","Ashe","Vayne","Twitch","Lucian","MissFortune","Ezreal","Jhin","Varus","Tristana","Caitlyn","Rakan","Nami","Sona","Soraka","Morgana","Lux","Janna","Brand","Fiddlesticks","Leona","Alistar","VelKoz","Zyra","Braum","Blitzcrank","Bard","Taric"]

// selecteur html
const clavier = document.querySelector('#clavier')
const usedContainerHtml = document.querySelector('.usedContainer')
const hideHtml = document.querySelector('#hide')
const drawHtml = document.querySelector('#draw')
const catchHtml = document.querySelector('.catch')

// variables configuration
var usedLetter = []
var life = 7
var  totalBarre = 0
const rand = Math.round(Math.random() * words.length)
let firstLetter=true

// initialisation du mot
const initWord = words[rand].toLowerCase()
const wordtoArray = initWord.split('')
var hideTab = wordToUnd(wordtoArray)

//Cheat
console.log(initWord)

// initialisation du clavier
for (let i = 0; i < alphabet.length; i++) {
	clavier.innerHTML += '<button class="btn btn-primary animated" id="' + alphabet[i] + '" onclick=run("' + alphabet[i] + '")>' + alphabet[i] + '</button>'
}

// initialisation du graphisme du jeu
infoGame(hideTab, usedLetter, life, '')

//For hint
let nbOcc=0
let avancement = 100/initWord.length
let hintStatus=false

//Chronometer
var time = 0;
var running = false;


// -----------------------------------------------------------
//                     FIN INITIALISATION
// -----------------------------------------------------------



// -----------------------------------------------------------
//                      FUNCTIONS
// -----------------------------------------------------------

function wordToUnd(word){
	let tabU = word.reduce((acc, _) => acc.concat('_') ,[])
	return tabU
}

function run(letter){
	if (firstLetter) {
		startPause()
		firstLetter=false
	}
	document.querySelector("#" + letter).setAttribute('disabled', true)
	document.querySelector("#" + letter).classList.remove('btn-primary')
	let isInW = isInWord(letter, hideTab, wordtoArray)
	if (!isInW) {
		document.querySelector("#" + letter).classList.add('btn-danger')
		document.querySelector("#" + letter).classList.add('flipOutX')
		usedLetter.push(letter)
		life--
	}else{
		document.querySelector("#" + letter).classList.add('btn-success')
		document.querySelector("#" + letter).classList.add('pulse')
		letter = ''
		move();
	}
	infoGame(hideTab, usedLetter, life, letter)
}

function isInWord(letter, hideTab, wordtoArray){
	var isIn = false
	for (let i = 0; i < wordtoArray.length; i++) {
		if (letter === wordtoArray[i]) {
			isIn = true
			hideTab[i] = wordtoArray[i]
			nbOcc++
		}
	}
	return isIn
}

function infoGame(hideTab, usedLetter, life, letter){
	hideHtml.innerHTML = hideTab.join(' ')
	let image = imageTab[life]
	drawHtml.innerHTML = '<img src="'+image+'" alt="hangman" />'
	if (letter.length) {
		catchHtml.innerHTML = '<button class="btn btn-danger animated flipInX">' + letter + '</button>'  
		setTimeout(function(){usedContainer(usedLetter)}, 1000);
	}
	if (life === 0) {
		hideHtml.innerHTML = 'Perdu le mot était : ' + initWord
		clavier.innerHTML = '<button class="btn btn-warning rubberBand text-white animated" onclick=document.location.reload()>Rejouer</button>'
	}
	if (!hideTab.includes('_')) {
		hideHtml.innerHTML = 'Gagné le mot était : ' + initWord
		clavier.innerHTML = '<button class="btn btn-success zoomIn text-white fast animated" onclick=document.location.reload()>Rejouer</button>'
		totalBarre += avancement
		hintStatus=true
		startPause()
	}
}

function usedContainer(usedLetter){
	usedContainerHtml.innerHTML = ''
	for (let i = 0; i < usedLetter.length; i++) {
		usedContainerHtml.innerHTML += '<button class="btn btn-danger">' + usedLetter[i] + '</button>'
	}
	catchHtml.innerHTML = ''  
}
// expected output: a number between 0 and 1

//For progress bar
function move(letter,wordtoArray) {
	var elem = document.getElementById("myBar");
	totalBarre += (nbOcc * avancement)
	nbOcc=0
	var id = setInterval(frame, 10);
	function frame() {
		if (totalBarre >= 100) { 
			clearInterval(id);
			elem.style.width = '100%'; //Due to total>100 when adding nbocc*avancement (manual)
		} else {
			elem.style.width = totalBarre + '%'; //If working normally
		}
	}
}

//Hint for the game
document.getElementById("btnHelp").onclick = function() {hint()};

function hint() {
	if (!hintStatus) {
		let hintLetter=wordtoArray[Math.floor(Math.random() * wordtoArray.length)]; // get rand letter from the word
		while(hideTab.includes(hintLetter)) 										// If the letter is alerdy displayed
			hintLetter=wordtoArray[Math.floor(Math.random() * wordtoArray.length)]; // Retry another letter
		run(hintLetter)
		hintStatus=true
		document.getElementById("btnHelp").innerHTML = "Vous avez utilisé votre indice 🤫";
	}
}

//Startwatch

function startPause(){
	if(!running){
		running = true;
		increment()
	}else{
		running = false;
	}
};

function increment(){
	if(running){
		setTimeout(function(){
			time++;
			var mins = Math.floor(time / 10 / 60);
			if(mins <= 9){
				mins = "0" + mins;
			}
			var secs = Math.floor(time / 10);
			if(secs <= 9){
				secs = "0" + secs;
			}
			if (secs>=60) {
				secs="0";
				mins++;
			}
			document.getElementById("cronos").innerHTML = mins + ":" + secs;
			increment();
		}, 100);
	}
};

